config/routes.rb
Rails.application.routes.draw do

  devise_for :users
   resources :products

  get 'contact/index'
  resources :posts do
 	resources :comments
 end
 devise_for :admins
 get "posts" => "posts#index", :as => 'blog'
root 'website#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
		 validates :title, presence: true, length: {minimum: 5}
		 validates :body , presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, except: :sign_in

  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		 
		 redirect_to post_path(@post)
		end 

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] 
  def index
  	@posts = Post.all.order('created_at DESC')
  end

  def show
  	@post = Post.find(params[:id])

  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  
    if @post.save
     redirect_to @post
   else
     render 'new'
  end
   end
     def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :sub_title, :body))
      redirect_to @post
    else
  render 'edit'
  end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end
  
  private
  	def post_params
  		params.require(:post).permit(:title, :sub_title, :body)
  	end
 

 


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :new, :create]
  def index
    @products = Product.all.order('created_at DESC')
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(pramas[:id])
    if @product.upadate(params[:product].permit(:title, :order, :description, :delivery, :price, :email))
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to  @product
  end

  private
  def product_params
    params.require(:product).permit(:title, :order, :description, :delivery, :price)
  end

end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
	<div class="panel panel-success">
		<div class="panel-heading">
			<h1 class="panel-title">
				<%= comment.name %>
				</h1>
		</div>

		<div class="panel-body post-preview">
			<%= comment.body %>
			<p class="post-meta">
		  	<%= time_ago_in_words(comment.created_at) %> Ago 
	
		<hr>
		<% if user_signed_in? %>
			<p><%= link_to 'Delete', [comment.post, comment],method: :delete, class: "btn btn-xs btn-default", data: { confirm: 'Are you sure?' }  %>
			</p>
			<% end %>
		</div>			
			

		
	</div>


</div>

app/views/comments/_form.html.erb
<div class="post-preview">
<%= form_for ( [@post, @post.comments.build] ), :html => {:class => "form-horizontal center"} do |f|  %>
	<div class="form-group">
		 <%= f.label :name, class: "col-md-1 control-label" "Name:" %>
		 
	</div>
	<div class="col-md-8">
	<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group" >
		<%= f.label :body, class: "col-md-8" %>
		</div>
		<div class="col-md-8">
		<%= f.text_area :body, class: "form-control", :rows => 5, :cols => 10  %></br>
	</div>

	<div class="col-md-8">
		<%= f.submit :submit, class: "btn btn-default" %>
	
		</div>
          <% end %>
</div>

app/views/contact/index.html.erb
<header class="intro-header" style="background-image: url('../assets/HNCK9016.jpg');" >
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 style="color: white; ">About Us</h1>
                    <hr class="small">
                    <span class="subheading">We are who we are, what we are, and when we are </span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
<h2 class="text-center">
What we do  </h2>
<div class="post-preveiw">
<p class="post-meta text-center">
  We are a set groups of developers  well specialized in Ruby on Rails, PHP, Software managment, Researchers and Journalists. We help you achieve what you want and what you desire with reduced number of risks in the field. We have worked in our different respective job areas and companies so we have all it takes to serve you better

</p>
<h2 class="text-center">
  Contact Us On
</h2>


</p>
</div>
<div class="container">
  <div class="row">

    <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12">
      <a href="#" class="fh5co-feature to-animate">
        <span class="fh5co-feature-icon"><%= fa_icon "skype" %></span>
        <h3 class="fh5co-feature-lead">Skype   </h3>
        <p class="fh5co-feature-text">here we will interact with you while building your work or respective orders</p>
      </a>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12">
      <a href="#" class="fh5co-feature to-animate">
        <span class="fh5co-feature-icon"><%= fa_icon "mobile-phone" %></span>
        <h3 class="fh5co-feature-lead">mobile</h3>
        <p class="fh5co-feature-text">You can contact our mobile for one on one order requests and questions</p>
      </a>
    </div>
    <div class="clearfix visible-sm-block"></div>
    <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12">
      <a href="posts/index.html.erb" class="fh5co-feature to-animate">
        <span class="fh5co-feature-icon"><%= fa_icon "envelope" %></span>
        <h3 class="fh5co-feature-lead">E-mail</h3>
        <p class="fh5co-feature-text">you can send us an Email on Whatever probelms and Questions you may Have  </p>
          <p class="fh5co-feature-text">fortune.chibuike1@gmail.com </p>
      </a>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12">
      <a href="#" class="fh5co-feature to-animate">
        <span class="fh5co-feature-icon"><%= fa_icon "facebook"%></span>
        <h3 class="fh5co-feature-lead">facebook</h3>
        <p class="fh5co-feature-text">Our facebook page exculsive for your order reviews for the world to see how good we are </p>
      </a>
    </div>

    <div class="clearfix visible-sm-block"></div>


      </div>
   </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://code.jquery.com/jquery-3.0.0.js"></script>
  <script src="https://code.jquery.com/jquery-migrate-3.0.0.js"></script>
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>FCODERS | Your all you need IT Tech & Developers</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Your all you need tool and friends that assure you 100% business, career or educatinal boost. we provide you with web app creation, SEO, Research, Links and News for our Blog this is the official sites of fcoders" />
	<meta name="keywords" content="Web,& Mobile developers html5, css3, mobile first, responsive, darknet journalist, SEO, BLOG NEWS, webmail/SMTP " />
	<meta name="author" content="FCODERS.ml" />
  <meta property=”og:title” content=”Fcoders official site for your use and buisness boost”/>
  <meta property=”og:url” content=”http://fcoders.ml”/>
  <meta property=”og:description” content=”DO YOU WNNA GROW BIG IN JUST LITTLE TIME ?, BOOST YOUR BUISNESS, CAREER, EDUCATION, LIFE EASILY HERE AT FCODERS”/>

    <!-- Bootstrap Core CSS -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <%= link_to "F-coders", root_path, class: "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to "Home", root_path %>
                    </li>
                    <li>
                      <%= link_to "Orders", products_path %>
                    <li>
                      <%= link_to "Blog", blog_path %>
                    <% if user_signed_in? %>
                    <li>
                    <%= link_to "Admin", new_post_path %>
                    </li>
                    <li>
                    <%= link_to "log out", destroy_user_session_path, :method => :delete %>
                    <% end %>

                    <li>
                       <%= link_to "Contact Us", contact_index_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->



                     <%= yield %>

            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">

                  <%= link_to Admin, new_user_session_path %><p class="copyright text-muted"> &copy; Fortunes creations 2016</p>
                    <p class="fh5co-social-icons">
                      <a href="#"><%= fa_icon "facebook" %></a>
                      <a href="#"><%= fa_icon "twitter" %></a>
                      <a href="#"><%= fa_icon "skype" %></a>
                      <a href="#"><%= fa_icon "icq" %></a>
                      <a href="#"><%= fa_icon "whatsapp" %></a>
                    </p>
                </div>
            </div>
        </div>
    </footer>






</body>
</html>

app/views/posts/_form.html.erb
	<%= simple_form_for @post, url: posts_path do |f| %>
     <%= f.input :title, as: :string %>
		<%= f.input :sub_title, as: :pagedown, :rows => 5, :cols => 18  %>
   	<%= f.input :body, as: :pagedown, :rows => 16, :cols => 16 %>
		<%= f.submit :submit, class: "btn btn-default" %>

	 <% end %>

app/views/posts/edit.html.erb
<div class="post-preview">

<h1 class="post-subtitle"> Edit Post </h1>

<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<header class="intro-header" style="background-image: image-url('home-bg.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 style="color: white">F-coders Blog</h1>
                    <hr class="small">
                    <span class="subheading"> Developers And News Blog</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
<% @posts.each do |post| %>
<div class="container">
<div class="row">
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<div class="post-preveiw">
<h3 class="post-title">
<%= link_to post.title, post %>
</h3>
<p class="post-meta"><%= post.sub_title %> </p>
<p class="post-meta"><%= post.created_at.strftime("%b, %d, %y") %></p>

</div>
</div>
</div>
</div>
<% end %>

app/views/posts/new.html.erb
<header class="intro-header" style="background-image: image-url('home-bg.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 style="color: white">F-coders Blog</h1>
                    <hr class="small">
                    <span class="subheading">Developers And News Blog</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
<div class="container">
<div class="post-preview">
<h1> Add Posts</h1>
<div class="row">
<div class="col-md-8">

<%= render 'form' %>

</div>
</div>
</div>
</div>

app/views/posts/show.html.erb
<header class="intro-header" style="background-image: image-url('home-bg.jpg');">
		<div class="container">
				<div class="row">
						<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
								<div class="site-heading">
								    <h1 style="color: white">F-coders Blog</h1>
										<hr class="small">
										<span class="subheading">School Developers And News Blog</span>
								</div>
						</div>
				</div>
		</div>
</header>

<!-- Main Content -->
<div class="container">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
<div class="container">
<div class="row">
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
<div class="post-preview">
<h1 class="post-title">
<%= @post.title %>
</h1>

<p class="post-meta">
Submitted by admin at <%= time_ago_in_words(@post.created_at) %> Ago
<% if user_signed_in? %>
| <%= link_to 'Edit', edit_post_path(@post) %>
| <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure"} %>
<% end %>
</p>

<p class="post-body">
<%= @post.body %>
</p>
<div class="comments">
	<h2><%= @post.comments.count %> Comments </h2>
	<%= render @post.comments %>
	</div>
	<h3> Add a comment </h3>
	    <%= render "comments/form" %>
</div>
</div>
</div>
</div>
</div>

app/views/products/_form.html.erb
<%=simple_form_for @product, url: products_path do |f| %>

    <%= f.input :title, placeholder: " Your ProjectTitele" %>

    <%= f.input :order, placeholder: "Your Order title/request" %>
    <%= f.input :description, :as => :pagedown, :input_html => { :preview => true }, placeholder: "What you want, and how you want it with your email address " %>


    <%= f.input :delivery, placeholder: "how urgent do you need your delivery" %>

    <%= f.input :price, placeholder: "price in btc" %>



  <%= f.submit :submit, class: "btn btn-default" %>

<% end %>

app/views/products/index.html.erb
<header class="intro-header" style="background-image: url('../assets/1.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 style="color: white">Recent orders</h1>
                    <hr class="small">
                    <span class="subheading"> New And Completed Orders And Reviews</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div id="fh5co-pricing" data-section="pricing">
  <div class="container">
    <div class="row">
      <% @products.each do |product| %>
      <div class="col-md-8   to-animate fh5co-figure">

          <h3 class="fh5co-figure-lead text-center"><%= link_to product.title, product %></h3>
          <p class="fh5co-figure-text text-center"><%= product.description %></p>

      </div>
      <% end %>
    </div>
    </div>
    </div>


    				<div id="fh5co-pricing" data-section="pricing">
    					<div class="container">
    						<div class="row">
    							<div class="col-md-8 col-md-offset-2 fh5co-section-heading text-center">
    								<h2 class="fh5co-lead animate-single pricing-animate-1">Offers for everyone</h2>
    								<p class="fh5co-sub animate-single pricing-animate-2"></p>
    							</div>

    							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">
    							<%= link_to new_product_path, class: "fh5co-figure" do %>
    									<span class="fh5co-price">$15<span>/topic</span></span>
    									<h3 class="fh5co-figure-lead">Clear-net Research</h3>
    									<p class="fh5co-figure-text">Deep keywords research for any purposes, exampleProject topics, assignments and  web work</p>
    								<% end %>
    							</div>
    							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">
    									<%= link_to new_product_path, class: "fh5co-figure" do %>
    									<span class="fh5co-price">$30<span>/topic/links</span></span>
    									<h3 class="fh5co-figure-lead">Deep web Research</h3>
    									<p class="fh5co-figure-text">we also offer deep-web research and links in other for our customers to avoid scammers and fake news its for educational purposes only</p>
    									<% end %>
    							</div>
    							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">
    								<%= link_to new_product_path, class: "fh5co-figure" do %>
    									<span class="fh5co-price">$25<span>/webmail/SMTP</span></span>
    									<h3 class="fh5co-figure-lead">Webmail/SMTP</h3>
    									<p class="fh5co-figure-text">Configured and tested webmails and SMTPS are also avaliable for sell</p>
    								<% end %>
    							</div>
    							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">

    										<%= link_to new_product_path, class: "fh5co-figure active pricing-feature" do %>
    									<span class="fh5co-price">$150<span>/prototype</span></span>
    									<h3 class="fh5co-figure-lead">Prototypes/cloning</h3>
    									<p class="fh5co-figure-text">for educational purposes we can offer to clone websites of your choice. note we only host clones on special request</p>
    								<% end %>
    							</div>
    							<div class="col-md-8 col-md-offset-2 to-animate">
    							<%= link_to new_product_path, class: "fh5co-figure" do %>
    									<span class="fh5co-price">$200<span>/Full websites</span></span>
    									<h3 class="fh5co-figure-lead">fully responsive websites</h3>
    									<p class="fh5co-figure-text">We will create and host your dreams. we will create a moblie responsive and dynamic app </p>
    								<% end %>
    							</div>
    						</div>
    					</div>
    				</div>

app/views/products/new.html.erb
<header class="intro-header" style="background-image: url('../assets/1.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 style="color: white">Request a work</h1>
                    <hr class="small">
                    <span class="subheading"> Request Our services</span>
                    <span class="subheading"> Remeber to type in your Email </span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
  <div class="row text-center">
    <div class= "col-md-8 col-md-offset-2 col-xm-offset-2">
      <%= render 'form' %>
      </div
    </div>
  </div>

  				<div id="fh5co-pricing" data-section="pricing">
  					<div class="container">
  						<div class="row">
  							<div class="col-md-8 col-md-offset-2 fh5co-section-heading text-center">
  								<h2 class="fh5co-lead animate-single pricing-animate-1">Offers for everyone</h2>
  								<p class="fh5co-sub animate-single pricing-animate-2"></p>
  							</div>

  							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">
  							<%= link_to new_product_path, class: "fh5co-figure" do %>
  									<span class="fh5co-price">$15<span>/topic</span></span>
  									<h3 class="fh5co-figure-lead">Clear-net Research</h3>
  									<p class="fh5co-figure-text">Deep keywords research for any purposes, exampleProject topics, assignments and  web work</p>
  								<% end %>
  							</div>
  							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">
  									<%= link_to new_product_path, class: "fh5co-figure" do %>
  									<span class="fh5co-price">$30<span>/topic/links</span></span>
  									<h3 class="fh5co-figure-lead">Deep web Research</h3>
  									<p class="fh5co-figure-text">we also offer deep-web research and links in other for our customers to avoid scammers and fake news its for educational purposes only</p>
  									<% end %>
  							</div>
  							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">
  								<%= link_to new_product_path, class: "fh5co-figure" do %>
  									<span class="fh5co-price">$25<span>/webmail/SMTP</span></span>
  									<h3 class="fh5co-figure-lead">Webmail/SMTP</h3>
  									<p class="fh5co-figure-text">Configured and tested webmails and SMTPS are also avaliable for sell</p>
  								<% end %>
  							</div>
  							<div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 to-animate">

  										<%= link_to new_product_path, class: "fh5co-figure active pricing-feature" do %>
  									<span class="fh5co-price">$150<span>/prototype</span></span>
  									<h3 class="fh5co-figure-lead">Prototypes/cloning</h3>
  									<p class="fh5co-figure-text">for educational purposes we can offer to clone websites of your choice. note we only host clones on special request</p>
  								<% end %>
  							</div>
  							<div class="col-md-8 col-md-offset-2 to-animate">
  							<%= link_to new_product_path, class: "fh5co-figure" do %>
  									<span class="fh5co-price">$200<span>/Full websites</span></span>
  									<h3 class="fh5co-figure-lead">fully responsive websites</h3>
  									<p class="fh5co-figure-text">We will create and host your dreams. we will create a moblie responsive and dynamic app </p>
  								<% end %>
  							</div>
  						</div>
  					</div>
  				</div>

app/views/products/show.html.erb
<header class="intro-header" style="background-image: url('../assets/1.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1 style="color: white">Works</h1>
                    <hr class="small">
                    <span class="subheading">work data</span>

                </div>
            </div>
        </div>
    </div>
</header>





<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 ">
  <table class="table table-striped">
    <thead>
      <tr>
        <td>Date created_at </td>
        <td> Project title </td>
        <td> Order title </td>
        <td> description </td>
        <td> delivery </td>
        <td> price </td>
      </tr>
    </thead>
    <tbody>


        <tr>
          <td><%=  @product.created_at.strftime("%b, %d, %y") %></td>
          <td><%= @product.title %></td>
          <td><%= @product.order %></td>
          <td><%= @product.description %></td>
          <td><%= @product.delivery %> days</td>
          <td><%=@product.price %> btc</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
</div>

<div class="col-lg-8 col-lg-offset-5 col-md-10 col-md-offset-2">
  <% if user_signed_in? %>
 <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-default" %>
 <%= link_to 'Delete', product_path(@product), method: :delete, class: "btn btn-warning", data: {confirm: "Are you sure"} %>
  <% end %>
</div>